//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeregrinosJMJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class actividades
    {
        public actividades()
        {
            this.inversion = new HashSet<inversion>();
            this.asistencia = new HashSet<asistencia>();
        }
    
        public int id_actividad { get; set; }
        public string actividad { get; set; }
        public System.DateTime fecha { get; set; }
        public string lugar { get; set; }
        public Nullable<float> ganacia { get; set; }
    
        public virtual ICollection<inversion> inversion { get; set; }
        public virtual ICollection<asistencia> asistencia { get; set; }
    }
}
