//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeregrinosJMJ
{
    using System;
    using System.Collections.Generic;
    
    public partial class inversion
    {
        public int id_inversion { get; set; }
        public string producto { get; set; }
        public float monto { get; set; }
        public int id_actividad { get; set; }
    
        public virtual actividades actividades { get; set; }
    }
}
