//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PeregrinosJMJ
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class peregrinosjmjEntities : DbContext
    {
        public peregrinosjmjEntities()
            : base("name=peregrinosjmjEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<actividades> actividades { get; set; }
        public DbSet<asistencia> asistencia { get; set; }
        public DbSet<inversion> inversion { get; set; }
        public DbSet<peregrinos> peregrinos { get; set; }
        public DbSet<usuarios> usuarios { get; set; }
    }
}
